site: Hacking on the Horizon
url: https://h0th.lol
title: Hacking on the Horizon
description: Hacking on the Horizon
twitter:
  username: OrielOrielOriel
  card: summary

permalink: pretty

highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      
  - scope:
      path: "assets/images"
    values:
      image: true
