site: Hacking on the Horizon
title: Hacking on the Horizon
description: >-
  Oriel's personal site and blog.
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: America/Chicago
repo: https://github.com/OrielOrielOriel/site # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Oriana Elise Farrugia (she/her)
  bio: I like hacking, security code review, software dev, and cooking.
  username: oriel # general username
  github: OrielOrielOriel # github username
  twitter: OrielOrielOriel # twitter username
  email: your-email@email.com # email adress

# URL settings
url: "https://www.hackingonthehorizon.com" #
baseurl: "/" # leave blank if not wishd
permalink: "https://www.hackingonthehorizon.com"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


